#!/usr/bin/env python3
"""
Generate a summary statistics do-file for any survey in config.DATASETS.

Pipeline
--------
1. Load survey metadata from variable dictionary JSON
2. Filter to numeric universe by survey type + non_null_count
3. filter_truly_numeric: scan dataset → drop pure-text vars, keep numeric/convertible
4. Group by relevance condition
5. Save survey_metadata.dta alongside the variable dictionary
6. Generate three Stata code blocks (destring, stats, merge+export)
7. Assemble into <survey>_summary_stats.do

Usage
-----
    python create_summary_stats_dofile.py --survey <key>

    <key> must match an entry in config.DATASETS.
    The entry must have:
        data          → path to Stata .dta file
        output_json   → path to variable dictionary JSON (created by create_variable_dictionaries.py)
    Optional keys in the entry:
        output_do     → where to write the generated do-file
                        (default: same directory as data, named <key>_summary_stats.do)
        sumstats_dir_stata → Stata global value for ${sumstats_dir}
                        (default: same directory as output_json, using a placeholder global)

Config
------
    Edit config.py to add survey entries to the DATASETS dict, then run:
        python create_variable_dictionaries.py --survey <key>   # Phase 4
        python create_summary_stats_dofile.py  --survey <key>   # Phase 5
"""

import argparse
import io
import re
import sys
import warnings
from pathlib import Path

import pandas as pd
import pyreadstat

# Pull DATASETS from this project's config.py (same directory as this script)
sys.path.insert(0, str(Path(__file__).parent))
from config import DATASETS
from load_survey_metadata import (
    load_survey_metadata,
    get_numeric_universe,
    filter_truly_numeric,
    build_relevance_groups,
    save_survey_metadata_dta,
    write_destring_block,
    write_stats_blocks,
    write_merge_and_export,
)


def _generate_stata_preamble(
    survey_key: str,
    n_vars: int,
    n_groups: int,
    n_calls: int,
    sumstats_dir_stata: str,
    dta_filename: str,
) -> str:
    return f"""\
/******************************************************************************

 TITLE:        Summary statistics — {survey_key} survey
 GENERATED BY: scripts/misc/surveycto_extractor/create_summary_stats_dofile.py

 DESCRIPTION:  Computes N, mean, SD, min, p25, p50, p75, max for {n_vars:,}
               numeric survey variables across {n_groups} skip-logic groups
               ({n_calls} tabstat calls).
               Merges with survey metadata (label, type, skip logic) and
               exports to sumstats_final.dta and sumstats_final.xlsx.

               Inputs:
               - ${{input_data}}/{dta_filename}  [TODO: adjust global if needed]
               - ${{sumstats_dir}}/survey_metadata.dta  (written by Python script)

               Outputs:
               - ${{sumstats_dir}}/sumstats_raw.dta
               - ${{sumstats_dir}}/sumstats_final.dta
               - ${{sumstats_dir}}/sumstats_final.xlsx

******************************************************************************

********************************************************************************
                             0. SET UP
*******************************************************************************/

global sumstats_dir "{sumstats_dir_stata}"

use "${{input_data}}/{dta_filename}", clear

"""


def _section(title: str) -> str:
    bar = "*" * 80
    return f"\n{bar}\n* {title}\n{bar}\n\n"


def identify_zero_obs_groups(groups: dict, dta_path: str,
                             parquet_path: str = None) -> set:
    """
    Load the dataset and count observations matching each group condition.
    Returns a set of condition strings that match zero observations.

    Uses parquet sidecar when available (faster columnar access).
    """
    try:
        if parquet_path:
            df = pd.read_parquet(parquet_path)
        else:
            df, _ = pyreadstat.read_dta(dta_path)
    except Exception as e:
        print(f"  WARNING: could not load dataset for zero-obs check: {e}")
        return set()

    zero_groups: set = set()

    for cond in groups:
        if not cond:
            continue

        # Translate Stata missing() syntax to pandas-compatible expressions
        expr = cond
        expr = re.sub(r'!missing\((\w+)\)', r'(\1 == \1)', expr)
        expr = re.sub(r'missing\((\w+)\)', r'(\1 != \1)', expr)

        # Check that at least one referenced variable exists in the dataset
        var_names = {v for v in re.findall(r'\b([a-zA-Z_]\w*)\b', expr)
                     if v in df.columns}
        if not var_names:
            print(f"  UNEVALUABLE (no matching cols): if {cond[:80]}...")
            continue

        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                mask = df[list(var_names)].eval(expr, engine='python')
            n_obs = int(mask.sum())
            if n_obs == 0:
                zero_groups.add(cond)
        except Exception as exc:
            print(f"  UNEVALUABLE ({exc.__class__.__name__}): if {cond[:80]}...")

    return zero_groups


def generate(survey_key: str) -> None:
    if survey_key not in DATASETS:
        print(f"ERROR: '{survey_key}' not found in config.DATASETS. "
              f"Available keys: {', '.join(DATASETS.keys())}")
        sys.exit(1)

    cfg = DATASETS[survey_key]
    json_path  = str(cfg['output_json'])
    dta_path   = str(cfg['data'])
    meta_dta   = str(Path(cfg['output_json']).parent / "survey_metadata.dta")

    # Output do-file location: explicit cfg key OR default next to data file
    if 'output_do' in cfg:
        output_do = Path(cfg['output_do'])
    else:
        output_do = Path(dta_path).parent / f"{survey_key}_summary_stats.do"

    # Stata global for sumstats_dir
    if 'sumstats_dir_stata' in cfg:
        sumstats_dir_stata = cfg['sumstats_dir_stata']
    else:
        # Use the same directory as the JSON, expressed as a literal path.
        # TODO: Replace this with a Stata global (e.g. ${project_root}/docs/...)
        # that matches your project's directory structure.
        sumstats_dir_stata = str(Path(cfg['output_json']).parent)

    dta_filename = Path(dta_path).name

    # ------------------------------------------------------------------
    # Python pipeline
    # ------------------------------------------------------------------
    print(f"=== Step 1: Load survey metadata ({survey_key}) ===")
    df = load_survey_metadata(json_path)

    print("\n=== Step 2: Get numeric universe ===")
    numeric_df = get_numeric_universe(df)

    print("\n=== Step 3: filter_truly_numeric (scan dataset) ===")
    # Use parquet sidecar if create_variable_dictionaries.py already wrote one
    pq_path = Path(dta_path).with_suffix('.parquet')
    pq_arg = str(pq_path) if pq_path.exists() else None
    convertible, non_convertible = filter_truly_numeric(numeric_df, dta_path, parquet_path=pq_arg)

    stats_df    = numeric_df.drop(index=non_convertible, errors="ignore")
    destring_df = numeric_df.loc[numeric_df.index.isin(convertible)]

    print(f"\n  -> destring_df : {len(destring_df):,} vars  (convertible strings only)")
    print(f"  -> stats_df    : {len(stats_df):,} vars  (full tabstat universe)")

    print("\n=== Step 4: Build relevance groups ===")
    _, dta_meta = pyreadstat.read_dta(dta_path, metadataonly=True)
    valid_cols   = frozenset(dta_meta.column_names)
    raw_str_cols = frozenset(
        col for col, vtype in dta_meta.readstat_variable_types.items()
        if vtype == "string"
    )
    string_cols = raw_str_cols - frozenset(convertible)
    groups = build_relevance_groups(stats_df, valid_cols=valid_cols, string_cols=string_cols)

    print(f"\n=== Step 4.5: Identify zero-observation groups ===")
    zero_groups = identify_zero_obs_groups(groups, dta_path, parquet_path=pq_arg)
    if zero_groups:
        print(f"  {len(zero_groups)} group(s) with 0 observations — will be commented out:")
        for cond in sorted(zero_groups):
            print(f"    if {cond[:100]}...")
    else:
        print("  All groups have observations — none skipped")

    print(f"\n=== Step 5: Save survey_metadata.dta ===")
    save_survey_metadata_dta(df, meta_dta)

    # ------------------------------------------------------------------
    # Generate Stata code blocks
    # ------------------------------------------------------------------
    print("\n=== Step 6: Generate Stata code blocks ===")
    buf = io.StringIO()
    sys.stdout = buf
    destring_code = write_destring_block(destring_df, mvdecode_universe=stats_df)
    stats_code    = write_stats_blocks(groups, zero_groups=zero_groups)
    merge_code    = write_merge_and_export()
    sys.stdout = sys.__stdout__

    # Route all outputs to ${sumstats_dir}
    stats_code = stats_code.replace("${analysis_data}", "${sumstats_dir}")
    merge_code = merge_code.replace("${analysis_data}", "${sumstats_dir}")

    diagnostics = buf.getvalue()
    n_groups_line = next(
        (l for l in diagnostics.splitlines() if "Total relevance groups" in l), ""
    )
    n_calls_line = next(
        (l for l in diagnostics.splitlines() if "Total tabstat calls" in l), ""
    )
    print(f"  {n_groups_line.strip()}")
    print(f"  {n_calls_line.strip()}")

    # ------------------------------------------------------------------
    # Assemble do-file
    # ------------------------------------------------------------------
    n_vars   = len(stats_df)
    n_groups = len(groups)
    n_calls  = n_groups  # default: one tabstat call per group
    for line in stats_code.splitlines():
        if "tabstat calls total" in line:
            try:
                n_calls = int(line.split()[3].replace(",", ""))
            except Exception:
                pass
            break

    preamble = _generate_stata_preamble(
        survey_key, n_vars, n_groups, n_calls,
        sumstats_dir_stata, dta_filename
    )

    do_content = "\n".join([
        preamble,
        _section("1. DESTRING AND SENTINEL RECODE"),
        destring_code,
        _section("2. SUMMARY STATISTICS"),
        stats_code,
        _section("3. MERGE METADATA AND EXPORT"),
        merge_code,
    ])

    output_do.parent.mkdir(parents=True, exist_ok=True)
    output_do.write_text(do_content, encoding="utf-8")

    size_kb = output_do.stat().st_size / 1024
    print(f"\n=== Done ===")
    print(f"Do-file  : {output_do}  ({size_kb:.0f} KB)")
    print(f"Metadata : {meta_dta}")
    print(f"\nTODO: Verify the Stata globals in the preamble match your project:")
    print(f"  ${{input_data}}   — must point to the directory containing {dta_filename}")
    print(f"  sumstats_dir  — currently set to:")
    print(f"    {sumstats_dir_stata}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate summary statistics do-file for a survey'
    )
    parser.add_argument(
        '--survey', required=True, metavar='KEY',
        help='Survey key from config.DATASETS (e.g. my_survey, baseline, endline)'
    )
    args = parser.parse_args()
    generate(args.survey)


if __name__ == "__main__":
    main()
