"""One repo-hygiene invariant: no tracked file cites a path that does not exist.

Nothing executes a docstring or a README, so a reference that rots is invisible to
the rest of the suite. This is the check that found `docs/coding_guidelines/...`
cited from `transformers/logic_converter.py`, where the real path has no `docs/`
prefix.

Deliberately ONE test rather than the three-sweep, self-ablating script this
replaces. Adversarial review of that script found it reported PASS on 20+ injected
defects, FAIL on three ordinary path-building idioms, and -- worst -- kept its
ablation green while the sweep it certified was broken, because the injected probe
only ever exercised the one shape already known to work. A small check that can be
read in full beats a large one whose self-verification is circular.

Two properties that version got wrong, both fixed here:

- **Matches must end at a path boundary.** `f"docs/report_{sha}.md"` and
  `"docs/x.md" % n` and implicit string concatenation all leave a truncated
  prefix, which the old regex reported as a dead path -- including one case where
  the real file existed. The trailing `(?![\\w-])` is what makes those inert.
- **Resolution must be case-EXACT.** The old version called `Path.exists()`, which
  is case-insensitive on Windows, so a wrong-case reference passed locally and was
  dead on Linux CI -- exactly the locally-green/CI-red class it was written to stop.
"""

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Reference classes that legitimately do not resolve in a clean checkout. Stored
# with a trailing slash and matched on the segment boundary, so an allowed prefix
# cannot suppress a dead sibling (`sample/output_dead.json` is NOT `sample/output/`).
ALLOWED = {
    ".claude/": "where the user COPIES the skill to; .claude/ is gitignored here",
    "data/": "the user's own gitignored data tree; references are instructions",
    "sample/output/": "generated by the sample pipeline, so absent until it runs",
    "scripts/accept_dep_prs.py": "lives in the external dep-accept skill checkout",
    "scripts/cleaning/": "a commented-out config example for a user's own project",
}

_ROOTS = (
    "src|tests|scripts|docs|coding_guidelines|skill|sample|data|[.]github|[.]claude"
)
PATH_RE = re.compile(
    rf"(?<![\w./\\-])((?:{_ROOTS})/[A-Za-z0-9_./-]*[A-Za-z0-9])(?![\w-])"
)
READABLE = {".py", ".md", ".toml", ".yaml", ".yml", ".json", ".cfg", ".txt", ".example"}


def _tracked() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
    )
    return [ln for ln in out.stdout.splitlines() if ln.strip()]


def _on_disk() -> set[str]:
    """Case-exact relative paths, files and dirs, excluding .git and .venv."""
    return {
        p.relative_to(REPO_ROOT).as_posix()
        for p in REPO_ROOT.rglob("*")
        if ".git" not in p.parts and ".venv" not in p.parts
    }


def _allowed(ref: str) -> bool:
    return any(ref == k.rstrip("/") or ref.startswith(k) for k in ALLOWED)


def _dead_references(extra: tuple[str, ...] = ()) -> dict[str, set[str]]:
    """{unresolved path reference: the files naming it}.

    Scans TRACKED files only. An untracked file is not repo content yet, and by
    the time pre-commit runs it is staged, so it is visible then. `extra` exists
    for the ablation test, which must inject a probe without touching the index.
    """
    disk = _on_disk()
    dead: dict[str, set[str]] = {}
    for rel in [*_tracked(), *extra]:
        path = REPO_ROOT / rel
        if path.suffix not in READABLE or not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in PATH_RE.finditer(text):
            ref = match.group(1)
            if ref in disk or _allowed(ref):
                continue
            dead.setdefault(ref, set()).add(rel)
    return dead


def test_no_tracked_file_cites_a_missing_path():
    dead = _dead_references()
    detail = "; ".join(
        f"{r} <- {', '.join(sorted(s))}" for r, s in sorted(dead.items())
    )
    assert not dead, f"{len(dead)} dead path reference(s): {detail}"


def test_the_check_reports_an_injected_dead_reference(tmp_path):
    """The detector must be shown to fire, on each shape it claims to catch.

    A single probe proves only that one shape works -- which is how the previous
    version stayed green while broken. Each case here is asserted separately.
    """
    probe = REPO_ROOT / "docs" / f"_probe_{tmp_path.name}.md"
    probe.write_text(
        "src/surveycto_extractor/never_existed.py\n"
        "tests/no_such_test.py\n"
        "skill/absent_helper.py\n",
        encoding="utf-8",
    )
    rel = probe.relative_to(REPO_ROOT).as_posix()
    try:
        dead = _dead_references(extra=(rel,))
    finally:
        probe.unlink(missing_ok=True)
    for expected in (
        "src/surveycto_extractor/never_existed.py",
        "tests/no_such_test.py",
        "skill/absent_helper.py",
    ):
        assert expected in dead, f"the sweep did not report {expected}"


def test_path_building_idioms_are_not_reported():
    """The false positives that would have blocked a legitimate commit."""
    real = "docs/synthetic-generator.md"
    assert (REPO_ROOT / real).is_file(), "fixture assumption: this doc exists"
    for snippet in (
        'return f"docs/report_{sha}.md"',
        'return "docs/report_%s.md" % n',
        'return ("docs/synthetic-" "generator.md")',
    ):
        disk = _on_disk()
        unresolved = [
            m.group(1)
            for m in PATH_RE.finditer(snippet)
            if m.group(1) not in disk and not _allowed(m.group(1))
        ]
        assert not unresolved, f"{snippet!r} wrongly reported {unresolved}"


def test_resolution_is_case_exact():
    """A wrong-case reference is dead on Linux and must not pass on Windows."""
    disk = _on_disk()
    assert "docs/synthetic-generator.md" in disk
    assert "docs/Synthetic-Generator.md" not in disk


def test_an_allowed_prefix_does_not_suppress_a_dead_sibling():
    # `sample/output/` is allowed; `sample/output_dead.json` is a different path.
    assert _allowed("sample/output/x_questions.json")
    assert not _allowed("sample/output_dead.json")
    assert not _allowed("scripts/no_such_helper.py")
