"""Survey lookup tool — project-agnostic version.

Auto-discovers survey documentation by scanning the docs directory for
variable_dictionary.json and questions.json files.

Usage:
  python search_survey.py --var <variable_name> [--context N]
  python search_survey.py --choice-list <list_name>
  python search_survey.py --search <text>
  python search_survey.py --gate-chain <variable_name>
  python search_survey.py --neighborhood <variable_name> [--depth N]
  python search_survey.py --repeat-tree

Options:
  --context N   Also print N adjacent questions on each side in survey order,
                plus resolve the relevance gate ("why is this asked").
                Default: 0 (off). Recommended: 3.
  --depth N     Neighborhood traversal depth (default: 1). Only with --neighborhood.

Search uses TF-IDF cosine similarity — natural-language queries like
"crop sales quantity" find abbreviated variables like crpsale_qty.

For --var lookups, performs a two-pass search:
  1. variable_dictionary.json  (keyed by Stata dataset name)
     -> resolves the SurveyCTO original_variable_name if it differs
  2. questions.json             (keyed by SurveyCTO form name)
     -> provides constraint, choices, relevance (not in the dictionary)
This ensures variables with name mismatches between SurveyCTO and Stata are found.

For --neighborhood lookups, loads the variable relationship graph
(*_variable_graph.json, generated by surveycto-vardict)
and returns all variables within N hops, grouped by edge type:
  - calculates_from: derived values (sentinel contamination risk)
  - gated_by / group_gated_by: relevance gating (missing-by-logic risk)
  - constrained_by: validation constraints
  - repeat_sibling: co-occur in same repeat iteration
Requires networkx (pip install networkx).

For --repeat-tree, shows the repeat group topology tree from the variable
graph: parent-child nesting, count variables, max iterations, Stata suffix
patterns, and join key notes.

SETUP:
  Option A — Auto-discovery (recommended):
    Set DOCS below to your project's survey_documentation root directory.
    The script will find all *_variable_dictionary.json / *_questions.json pairs.

  Option B — Manual SURVEY_FILES dict:
    Comment out the _auto_discover_surveys call and set SURVEY_FILES directly
    (see commented example below).
"""

import argparse
import json
import math
import re
import sys
import unicodedata
from pathlib import Path

# Guard against Windows cp1252 encoding errors on non-ASCII output
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ---------------------------------------------------------------------------
# Lightweight TF-IDF index (shared with the packaged MCP server)
# ---------------------------------------------------------------------------

# [^\W_] = any Unicode letter/digit but not underscore. ASCII-only [a-z0-9]
# shredded accented Spanish/French question text so it never matched. (#29.4)
_TOKEN_RE = re.compile(r"[^\W_]{2,}", re.UNICODE)


def _tokenize(text: str) -> list[str]:
    """Split text into lowercase tokens (>= 2 chars), accent-insensitive.

    NFKD-normalises and strips combining marks so accented and unaccented
    forms match both ways, then casefolds; non-Latin scripts are preserved.
    """
    norm = unicodedata.normalize("NFKD", text)
    norm = "".join(c for c in norm if not unicodedata.combining(c))
    return _TOKEN_RE.findall(norm.casefold())


class _TfidfIndex:
    """Minimal TF-IDF index for cosine-similarity search over text documents."""

    __slots__ = ("_doc_ids", "_doc_tfs", "_idf", "_doc_norms")

    def __init__(self, docs: list[tuple[str, str]]):
        self._doc_ids: list[str] = []
        self._doc_tfs: list[dict[str, float]] = []
        self._idf: dict[str, float] = {}
        self._doc_norms: list[float] = []
        self._build(docs)

    def _build(self, docs: list[tuple[str, str]]):
        n = len(docs)
        if n == 0:
            return
        df: dict[str, int] = {}
        for doc_id, text in docs:
            tokens = _tokenize(text)
            tf: dict[str, float] = {}
            for tok in tokens:
                tf[tok] = tf.get(tok, 0.0) + 1.0
            doc_len = len(tokens) or 1
            for tok in tf:
                tf[tok] /= doc_len
            self._doc_ids.append(doc_id)
            self._doc_tfs.append(tf)
            for tok in tf:
                df[tok] = df.get(tok, 0) + 1
        self._idf = {
            tok: math.log((n + 1) / (freq + 1)) + 1 for tok, freq in df.items()
        }
        for tf in self._doc_tfs:
            norm_sq = sum((w * self._idf.get(tok, 0.0)) ** 2 for tok, w in tf.items())
            self._doc_norms.append(math.sqrt(norm_sq) or 1.0)

    def query(
        self, text: str, max_results: int = 20, min_score: float = 0.01
    ) -> list[tuple[str, float]]:
        """Return top doc_ids ranked by cosine similarity to *text*."""
        tokens = _tokenize(text)
        if not tokens or not self._doc_ids:
            return []
        q_tf: dict[str, float] = {}
        for tok in tokens:
            q_tf[tok] = q_tf.get(tok, 0.0) + 1.0
        q_len = len(tokens)
        for tok in q_tf:
            q_tf[tok] /= q_len
        q_vec = {tok: w * self._idf.get(tok, 0.0) for tok, w in q_tf.items()}
        q_norm = math.sqrt(sum(v**2 for v in q_vec.values())) or 1.0
        scored: list[tuple[str, float]] = []
        for i, tf in enumerate(self._doc_tfs):
            dot = sum(
                q_vec.get(tok, 0.0) * w * self._idf.get(tok, 0.0)
                for tok, w in tf.items()
                if tok in q_vec
            )
            if dot <= 0:
                continue
            score = dot / (self._doc_norms[i] * q_norm)
            if score >= min_score:
                scored.append((self._doc_ids[i], score))
        scored.sort(key=lambda x: x[1], reverse=True)
        return scored[:max_results]


# ---------------------------------------------------------------------------
# CONFIGURATION — update DOCS to match your project layout
# ---------------------------------------------------------------------------
# This script lives at .claude/skills/survey-expert/search_survey.py
# REPO_ROOT is 3 levels up (skills/ -> .claude/ -> repo root).
REPO_ROOT = Path(__file__).resolve().parents[3]

# TODO: Update this path to your project's survey_documentation directory.
# Examples:
#   REPO_ROOT / "docs" / "endline" / "survey_documentation"
#   REPO_ROOT / "8. Baseline" / "survey_documentation"
DOCS = REPO_ROOT / "docs" / "survey_documentation"  # TODO: adjust


def _auto_discover_surveys(docs_dir: Path) -> dict:
    """Walk docs_dir, find *_variable_dictionary.json files, pair with questions.json.
    Returns dict: {label: {questions: Path, vardict: Path}}.
    """
    survey_files = {}
    if not docs_dir.exists():
        return survey_files
    for vdict_path in sorted(docs_dir.rglob("*_variable_dictionary.json")):
        stem = vdict_path.stem  # e.g. "girls_variable_dictionary"
        label = stem.replace("_variable_dictionary", "")
        q_path = vdict_path.parent / f"{label}_questions.json"
        if not q_path.exists():
            for candidate in vdict_path.parent.glob("*_questions.json"):
                q_path = candidate
                break
        if q_path.exists():
            survey_files[label] = {"questions": q_path, "vardict": vdict_path}
    return survey_files


SURVEY_FILES = _auto_discover_surveys(DOCS)

# ---------------------------------------------------------------------------
# Option B: override SURVEY_FILES manually if auto-discovery doesn't work.
# Example for a multi-instrument baseline project:
#
# DOCS_GIRLS = REPO_ROOT / "8. Baseline" / "survey_documentation" / "girls"
# DOCS_NORMS = REPO_ROOT / "8. Baseline" / "survey_documentation" / "norms"
# SURVEY_FILES = {
#     "girls": {
#         "questions": DOCS_GIRLS / "girls_questions.json",
#         "vardict":   DOCS_GIRLS / "girls_variable_dictionary.json",
#     },
#     "norms": {
#         "questions": DOCS_NORMS / "norms_questions.json",
#         "vardict":   DOCS_NORMS / "norms_variable_dictionary.json",
#     },
# }
# ---------------------------------------------------------------------------


def load_json(path: Path):
    """Load and return the JSON parsed from ``path``."""
    with open(path, encoding="utf-8") as f:
        return json.load(f)


MAX_DISPLAY_LEN = 200  # cap long text (consent relevance, group_relevances, etc.)


def _truncate(text: str, limit: int = MAX_DISPLAY_LEN) -> str:
    """Truncate text with a character count suffix if it exceeds limit."""
    if not text or len(text) <= limit:
        return text
    return text[:limit] + f" [...{len(text) - limit} more chars]"


def sentinel_note(choices, constraint):
    """Extract sentinel codes from choices list (negative values) or constraint string."""
    sentinels = []
    if choices:
        for c in choices:
            try:
                v = int(c["value"])
                if v < 0:
                    sentinels.append(f"{v} ({c['label'].strip()})")
            except (ValueError, KeyError):
                pass
    if constraint and not sentinels:
        for m in re.finditer(r"\.\s*=\s*(-\d+)", constraint):
            sentinels.append(m.group(1))
    return ", ".join(sentinels) if sentinels else "none"


def fmt_choices(choices):
    """Format a choice list as aligned ``value = label`` lines, or "n/a" if empty."""
    if not choices:
        return "n/a"
    parts = [f"  {c['value']:>4} = {c['label'].strip()}" for c in choices]
    return "\n" + "\n".join(parts)


def extract_gate_vars(relevance: str) -> list:
    """Parse all ${variable_name} references from a SurveyCTO relevance expression."""
    return re.findall(r"\$\{([^}]+)\}", relevance or "")


def fmt_gate_summary(gate_q: dict) -> str:
    """One-line summary of a gate variable: type, choices/constraint, its own relevance."""
    qt = (gate_q.get("question_text") or "").strip()
    cl = gate_q.get("choice_list") or ""
    choices = gate_q.get("choices") or []
    constraint = gate_q.get("constraint") or ""
    own_rel = gate_q.get("relevance") or ""
    grp_rels = gate_q.get("group_relevances") or []

    # Build a compact choices/constraint note
    if choices:
        choice_str = ", ".join(f"{c['value']}={c['label'].strip()}" for c in choices)
        type_note = f"[{cl}: {choice_str}]"
    elif constraint:
        type_note = f"[constraint: {constraint}]"
    else:
        type_note = f"[{gate_q.get('type', '?')}]"

    # Resolve own gate condition
    if own_rel:
        gate_note = f"asked when: {own_rel}"
    elif grp_rels:
        gate_note = f"asked when: {'; '.join(grp_rels)}"
    else:
        gate_note = "always asked"

    return f"    {_truncate(qt)}\n      {type_note}\n      {gate_note}"


def print_why_asked(q: dict, q_index: dict) -> None:
    """Resolve all gate variables in the relevance expression and print their details."""
    relevance = q.get("relevance") or ""
    grp_rels = q.get("group_relevances") or []

    # Collect all gate vars from both relevance and group_relevances
    gate_vars = extract_gate_vars(relevance)
    for gr in grp_rels:
        gate_vars += extract_gate_vars(gr)
    gate_vars = list(dict.fromkeys(gate_vars))  # deduplicate, preserve order

    if not gate_vars:
        return

    print("  why asked  :")
    for gvar in gate_vars:
        gate_q = q_index.get(gvar)
        if gate_q:
            print(f"    {gvar}:")
            print(fmt_gate_summary(gate_q))
        else:
            print(f"    {gvar}: (not found in questions.json)")


def print_context(questions: list, target_idx: int, n: int) -> None:
    """Print N adjacent questions on each side of target_idx in compact form."""
    if n <= 0:
        return

    start = max(0, target_idx - n)
    end = min(len(questions), target_idx + n + 1)

    print(f"\n  --- adjacent questions (survey order, context={n}) ---")
    for i in range(start, end):
        q = questions[i]
        vn = q.get("variable_name", "?")
        qt = (q.get("question_text") or "").strip()[:65]
        rel = q.get("relevance") or ""

        marker = ">>>" if i == target_idx else "   "
        print(f"  {marker} [{i:4d}] {vn}")
        print(f"           Q: {qt}")
        if rel:
            print(f"           relevance: {_truncate(rel)}")


def print_question(
    q: dict,
    survey_label: str,
    stata_name: str = None,
    questions: list = None,
    target_idx: int = None,
    context: int = 0,
    q_index: dict = None,
) -> None:
    """Print one question record with optional context and why-asked sections."""
    print(f"\n{'-' * 60}")
    form_name = q.get("variable_name", "?")
    if stata_name and stata_name != form_name:
        print(f"[{survey_label}]  stata: {stata_name}  (form: {form_name})")
    else:
        print(f"[{survey_label}]  {form_name}")

    stata_type = q.get("_stata_type")
    if stata_type:
        print(f"  stata_type : {stata_type}")
    non_null = q.get("_non_null_count")
    if non_null is not None:
        print(f"  non_null   : {non_null:,}")
    d_min = q.get("_data_min")
    d_max = q.get("_data_max")
    if d_min is not None and d_max is not None:
        print(f"  data_range : {d_min} to {d_max}")

    # Repeat group summary — ALWAYS shown first if applicable; critical for position-vs-code decisions
    ri = q.get("_repeat_info")
    if ri is not None:
        max_s = f"of {ri['max_iter']} (max observed)" if ri["max_iter"] else "of ?"
        print("  *** REPEAT GROUP ***")
        print(f"  repeat     : iteration {ri['iteration']} {max_s}")
        print(f"  repeat_grp : {ri['base']}  (count var: {ri['count_key']})")
        print(
            "  pos_vs_code: VERIFY -- if count is constant across HHs: position==code (safe)."
        )
        print(
            "               If count varies by HH (select_multiple-gated repeat): position!=code"
        )
        print("               (need routing variable to map position -> choice code).")
        print(
            f"               Check: tabulate {ri['count_key']} to see if count varies."
        )

    print(f"  form_type  : {q.get('type', '?')}")
    print(f"  question   : {(q.get('question_text') or '').strip()}")
    print(f"  choice_list: {q.get('choice_list') or 'none'}")
    cfilt = q.get("choice_filter")
    if cfilt:
        print(f"  ch_filter  : {str(cfilt).strip()}")
    print(f"  choices    : {fmt_choices(q.get('choices'))}")
    # If any choice carries filter-column dimensions, surface them on a
    # second line per choice so the structural partition is visible.
    ch = q.get("choices")
    if isinstance(ch, list):
        core_keys = {"value", "label"}
        extra = []
        for c in ch:
            if isinstance(c, dict):
                for k in c:
                    if k not in core_keys and k not in extra:
                        extra.append(k)
        if extra:
            for c in ch:
                if not isinstance(c, dict):
                    continue
                dims = [f"{k}={c[k]}" for k in extra if k in c]
                if dims:
                    print(
                        f"             {str(c.get('value', '')):>6} -> [{', '.join(dims)}]"
                    )
    print(f"  sentinels  : {sentinel_note(q.get('choices'), q.get('constraint'))}")
    print(f"  constraint : {q.get('constraint') or 'none'}")
    # Prefer vardict-merged stata_constraint; fall back to questions.json
    # for lookups by form name (no Stata-side variable matches).
    stc = q.get("_stata_constraint") or q.get("stata_constraint")
    if stc:
        print(f"  st_constr  : {stc}")
    print(f"  relevance  : {q.get('relevance') or 'none'}")
    grp = q.get("group_relevances") or []
    if grp:
        print(f"  grp_relev  : {'; '.join(grp)}")
    print(f"  skip_logic : {q.get('stata_skip_logic') or 'none'}")
    refs = q.get("_references") or q.get("references")
    if refs:
        print(f"  references : {', '.join(refs)}")
    path = q.get("group_path") or []
    print(f"  group_path : {' / '.join(path) if isinstance(path, list) else path}")

    # Why asked: resolve gate variables from relevance expression
    if q_index is not None:
        print_why_asked(q, q_index)

    # Adjacent questions in survey order
    if questions is not None and target_idx is not None and context > 0:
        print_context(questions, target_idx, context)


def _questions_by_name(questions: list) -> dict:
    """Build {variable_name: question_record} index."""
    return {q["variable_name"]: q for q in questions if "variable_name" in q}


def _filter_surveys(survey_filter: str = None) -> dict:
    """Return SURVEY_FILES filtered by --survey flag. Supports partial match."""
    if not survey_filter:
        return SURVEY_FILES
    matched = {k: v for k, v in SURVEY_FILES.items() if survey_filter in k}
    if not matched:
        print(
            f"WARNING: --survey '{survey_filter}' matched no surveys. "
            f"Available: {', '.join(SURVEY_FILES.keys())}",
            file=sys.stderr,
        )
    return matched


def search_var(stata_name: str, context: int = 0, survey_filter: str = None) -> bool:
    """Two-pass lookup:
      Pass 1 — variable_dictionary (Stata name -> original SurveyCTO name + Stata type)
      Pass 2 — questions.json (SurveyCTO name -> constraint, choices, relevance)
    Falls back to direct questions.json search if variable_dictionary is missing.
    """
    found = False
    for label, files in _filter_surveys(survey_filter).items():
        qpath = files["questions"]
        vpath = files["vardict"]
        if not qpath.exists():
            continue

        questions = load_json(qpath)
        q_index = _questions_by_name(questions)

        # Pass 1: variable_dictionary lookup
        original_name = stata_name
        stata_type = None
        non_null_count = None
        data_min = None
        data_max = None
        repeat_info = None  # filled below if variable is from a repeat group

        # Vardict-only data-structure fields lifted into the question dict
        # at the end of pass 1 (so print_question can render them).
        vdict_stata_constraint = None
        vdict_references = None
        vdict_choice_filter = None
        vdict_choices_with_filter_cols = None

        if vpath.exists():
            vardict = load_json(vpath).get("variables", {})
            entry = vardict.get(stata_name)
            if entry:
                stata_type = entry.get("stata", {}).get("type")
                non_null_count = entry.get("non_null_count")
                data_min = entry.get("data_min")
                data_max = entry.get("data_max")
                orig = entry.get("survey", {}).get("original_variable_name")
                if orig:
                    original_name = orig
                survey_blk = entry.get("survey", {}) or {}
                vdict_stata_constraint = survey_blk.get("stata_constraint")
                vdict_references = survey_blk.get("references")
                vdict_choice_filter = survey_blk.get("choice_filter")
                # The vardict choices block carries filter-column dimensions
                # on each row when the underlying choices sheet had them.
                vc = survey_blk.get("choices")
                if isinstance(vc, list):
                    vdict_choices_with_filter_cols = vc

                # Repeat group detection — surface position-vs-code info prominently
                repeat_iter = entry.get("repeat_iteration")
                if repeat_iter is not None:
                    # Derive max iteration from all variables sharing the same form name
                    sibling_iters = [
                        v.get("repeat_iteration")
                        for k, v in vardict.items()
                        if isinstance(v, dict)
                        and v.get("survey", {}).get("original_variable_name")
                        == original_name
                        and isinstance(v.get("repeat_iteration"), int)
                    ]
                    max_iter = max(sibling_iters) if sibling_iters else None

                    # Find the _count variable: search all vardict entries with
                    # type=="repeat_count" and a repeat_group_base that appears in
                    # the target variable's group_path.
                    gpath = entry.get("survey", {}).get("group_path", "") or ""
                    gpath_str = gpath if isinstance(gpath, str) else "/".join(gpath)
                    gpath_parts = [
                        p.strip() for p in gpath_str.replace("/", " ").split()
                    ]

                    count_key = None
                    count_entry = {}
                    for ck, cv in vardict.items():
                        if not isinstance(cv, dict):
                            continue
                        if cv.get("survey", {}).get("type") == "repeat_count":
                            base = cv.get("repeat_metadata", {}).get(
                                "repeat_group_base", ""
                            )
                            if base and base in gpath_parts:
                                count_key = ck
                                count_entry = cv
                                break
                    # Fallback: walk group_path from innermost outward, try <part>_count
                    if count_key is None:
                        for part in reversed(gpath_parts):
                            candidate = f"{part}_count"
                            if candidate in vardict:
                                count_key = candidate
                                count_entry = vardict[candidate]
                                break

                    # A FIXED repeat count means the count var is non-null for ALL HHs
                    # (i.e. the repeat always runs the same number of times).
                    # VARIABLE count = the repeat is driven by a prior select_multiple.
                    total_obs = (
                        load_json(vpath).get("dataset", {}).get("n_observations")
                    )
                    count_nonnull = (
                        count_entry.get("non_null_count") if count_entry else None
                    )
                    fixed = (
                        count_nonnull is not None
                        and total_obs is not None
                        and count_nonnull == total_obs
                    )
                    base_display = count_entry.get("repeat_metadata", {}).get(
                        "repeat_group_base"
                    ) or (count_key.replace("_count", "") if count_key else "?")
                    repeat_info = {
                        "iteration": repeat_iter,
                        "max_iter": max_iter,
                        "base": base_display,
                        "count_key": count_key or "?",
                        "fixed": fixed,
                    }

        # Pass 2: questions.json lookup by original SurveyCTO name
        q = q_index.get(original_name)
        if q is None and original_name != stata_name:
            q = q_index.get(stata_name)
        if q is None:
            continue

        # Find index for context printing
        try:
            target_idx = next(
                i
                for i, x in enumerate(questions)
                if x.get("variable_name") == q.get("variable_name")
            )
        except StopIteration:
            target_idx = None

        if stata_type:
            q = dict(q, _stata_type=stata_type)
        if non_null_count is not None:
            q = dict(q, _non_null_count=non_null_count)
        if data_min is not None and data_max is not None:
            q = dict(q, _data_min=data_min, _data_max=data_max)
        if repeat_info is not None:
            q = dict(q, _repeat_info=repeat_info)
        if vdict_stata_constraint:
            q = dict(q, _stata_constraint=vdict_stata_constraint)
        if vdict_references:
            q = dict(q, _references=vdict_references)
        if vdict_choice_filter and not q.get("choice_filter"):
            q = dict(q, choice_filter=vdict_choice_filter)
        # Prefer vardict choice rows when they carry filter-column dimensions
        # that questions.json's copy may have dropped.
        if vdict_choices_with_filter_cols:
            q.get("choices") or []
            if any(
                set(c.keys()) - {"value", "label"}
                for c in vdict_choices_with_filter_cols
                if isinstance(c, dict)
            ):
                q = dict(q, choices=vdict_choices_with_filter_cols)

        print_question(
            q,
            label,
            stata_name=stata_name if stata_name != original_name else None,
            questions=questions,
            target_idx=target_idx,
            context=context,
            q_index=q_index,
        )
        found = True

    return found


def search_choice_list(
    list_name: str, context: int = 0, survey_filter: str = None
) -> bool:
    """Print the choice list named ``list_name`` and the vars using it, across surveys."""
    found = False
    for label, files in _filter_surveys(survey_filter).items():
        qpath = files["questions"]
        if not qpath.exists():
            continue
        questions = load_json(qpath)
        q_index = _questions_by_name(questions)
        for i, q in enumerate(questions):
            if q.get("choice_list") == list_name:
                print_question(
                    q,
                    label,
                    questions=questions,
                    target_idx=i,
                    context=context,
                    q_index=q_index,
                )
                found = True
    return found


def search_text(text: str, context: int = 0, survey_filter: str = None) -> bool:
    """Search question text and labels for ``text`` and print matches across surveys."""
    found = False
    for label, files in _filter_surveys(survey_filter).items():
        qpath = files["questions"]
        vpath = files["vardict"]
        if not qpath.exists():
            continue
        questions = load_json(qpath)
        q_index = _questions_by_name(questions)

        # Build TF-IDF index: one document per question, text = var_name + question_text
        vardict = {}
        if vpath.exists():
            vardict = load_json(vpath).get("variables", {})

        tfidf_docs: list[tuple[str, str]] = []
        for q in questions:
            vn = q.get("variable_name") or ""
            qt = q.get("question_text") or ""
            tfidf_docs.append((vn, vn.replace("_", " ") + " " + qt))
        # Also index vardict variables not in questions (Stata-renamed vars)
        q_varnames = {d[0] for d in tfidf_docs}
        for var_name, entry in vardict.items():
            if var_name in q_varnames or not isinstance(entry, dict):
                continue
            survey_data = entry.get("survey", {})
            qt = survey_data.get("question_text") or ""
            form_name = survey_data.get("original_variable_name") or ""
            tfidf_docs.append(
                (
                    var_name,
                    var_name.replace("_", " ")
                    + " "
                    + qt
                    + " "
                    + form_name.replace("_", " "),
                )
            )

        idx = _TfidfIndex(tfidf_docs)
        hits = idx.query(text, max_results=20)

        for var_name, _score in hits:
            q = q_index.get(var_name)
            # If hit is a Stata-renamed variable, resolve to form name
            if q is None and var_name in vardict:
                form_name = (
                    vardict[var_name]
                    .get("survey", {})
                    .get("original_variable_name", "")
                )
                if form_name:
                    q = q_index.get(form_name)
            if q is None:
                continue
            try:
                target_idx = next(
                    i
                    for i, x in enumerate(questions)
                    if x.get("variable_name") == var_name
                )
            except StopIteration:
                target_idx = None
            print_question(
                q,
                label,
                questions=questions,
                target_idx=target_idx,
                context=context,
                q_index=q_index,
            )
            found = True
    return found


def gate_chain(stata_name: str, survey_filter: str = None) -> bool:
    """Build the full composed gate chain for a variable.

    Walks from group-level relevances (outermost) through the variable's
    own relevance, recursively resolving each ${ref} to its question text,
    choice list, and own gate condition.  Returns an indented tree.
    """
    found = False
    for label, files in _filter_surveys(survey_filter).items():
        qpath = files["questions"]
        vpath = files["vardict"]
        if not qpath.exists():
            continue

        questions = load_json(qpath)
        q_index = _questions_by_name(questions)

        # Find variable in vardict
        original_name = stata_name
        vardict = {}
        entry = {}
        if vpath.exists():
            raw = load_json(vpath)
            vardict = raw.get("variables", {})
            entry = vardict.get(stata_name, {})
            orig = entry.get("survey", {}).get("original_variable_name")
            if orig:
                original_name = orig

        # Get question from questions.json
        q = q_index.get(original_name)
        if q is None and original_name != stata_name:
            q = q_index.get(stata_name)
        if q is None and not entry:
            continue

        found = True

        # Collect all conditions: group relevances (outer->inner) + own
        grp_rels = []
        own_rel = ""
        if q:
            grp_rels = q.get("group_relevances") or []
            own_rel = q.get("relevance") or ""
        else:
            grp_rels = entry.get("survey", {}).get("group_relevances") or []

        all_conditions = list(grp_rels) + ([own_rel] if own_rel else [])

        lines = [f"[{label}] Gate chain for: {stata_name}"]

        if not all_conditions:
            lines.append("  (always asked -- no skip logic)")
            print("\n".join(lines))
            continue

        # Cache for resolved gate variables
        resolved_cache = {}

        def _resolve_var(vname):
            if vname in resolved_cache:
                return resolved_cache[vname]
            gq = q_index.get(vname)
            info = {"name": vname}
            if gq:
                info["question"] = (gq.get("question_text") or "").strip()[:80]
                info["type"] = gq.get("type") or "?"
                gchoices = gq.get("choices") or []
                gcl = gq.get("choice_list") or ""
                if gchoices:
                    cstr = ", ".join(
                        f"{c['value']}={c['label'].strip()}" for c in gchoices[:6]
                    )
                    info["choices"] = f"{gcl}: {cstr}"
                else:
                    info["choices"] = ""
                info["own_relevance"] = gq.get("relevance") or ""
            else:
                # Try vardict
                ve = vardict.get(vname, {})
                if ve:
                    sd = ve.get("survey", {})
                    info["question"] = (sd.get("question_text") or "").strip()[:80]
                    info["type"] = sd.get("type") or "?"
                    info["choices"] = ""
                    info["own_relevance"] = ""
                else:
                    info["question"] = "(not found in survey)"
                    info["type"] = "?"
                    info["choices"] = ""
                    info["own_relevance"] = ""
            resolved_cache[vname] = info
            return info

        indent = 0
        for i, cond in enumerate(all_conditions):
            is_group = i < len(grp_rels)
            prefix = "  " * indent
            source = "GROUP" if is_group else "VAR"

            refs = re.findall(r"\$\{([^}]+)\}", cond)
            display_cond = re.sub(r"\$\{([^}]+)\}", r"\1", cond)

            lines.append(f"{prefix}[{source}] {display_cond}")

            for ref in refs:
                rinfo = _resolve_var(ref)
                qt = rinfo.get("question", "")
                choices = rinfo.get("choices", "")
                own = rinfo.get("own_relevance", "")

                lines.append(f"{prefix}  ^ {ref}: {qt}")
                if choices:
                    lines.append(f"{prefix}    [{choices}]")
                if own:
                    own_display = re.sub(r"\$\{([^}]+)\}", r"\1", own)
                    lines.append(f"{prefix}    asked when: {own_display}")
                else:
                    lines.append(f"{prefix}    always asked")

            indent += 1

        # Final line: the target variable itself
        prefix = "  " * indent
        survey_data = entry.get("survey", {}) if entry else {}
        qt = (
            survey_data.get("question_text")
            or (q.get("question_text") if q else "")
            or ""
        ).strip()[:80]
        lines.append(f"{prefix}>>> {stata_name}: {qt}")

        # Non-null vs total
        non_null = entry.get("non_null_count")
        total = None
        if vpath.exists():
            total = load_json(vpath).get("dataset", {}).get("n_observations")
        if non_null is not None and total is not None:
            lines.append(f"{prefix}    non_null: {non_null:,} / {total:,}")

        print("\n".join(lines))

    return found


def variable_neighborhood(name: str, depth: int = 1, survey_filter: str = None) -> bool:
    """Show the variable relationship neighborhood from the dependency graph."""
    try:
        import networkx as nx
    except ImportError:
        print(
            "ERROR: networkx required for --neighborhood. Install: pip install networkx",
            file=sys.stderr,
        )
        return False

    found = False

    for label, files in _filter_surveys(survey_filter).items():
        vpath = files["vardict"]
        if not vpath.exists():
            continue

        # Find graph file next to vardict
        graph_path = vpath.with_name(
            vpath.stem.replace("_variable_dictionary", "_variable_graph") + ".json"
        )
        if not graph_path.exists():
            print(f"[{label}] No variable graph found at {graph_path}", file=sys.stderr)
            print(
                f"  Generate it: uv run surveycto-vardict --survey {label}",
                file=sys.stderr,
            )
            continue

        # Load graph and repeat tree
        with open(graph_path, encoding="utf-8") as f:
            raw_graph = json.load(f)
        repeat_tree = raw_graph.pop("repeat_groups", {})
        G = nx.node_link_graph(raw_graph)

        # Resolve Stata name to form-level name
        vardict = load_json(vpath).get("variables", {})
        form_name = name
        entry = vardict.get(name)
        if isinstance(entry, dict):
            form_name = entry.get("survey", {}).get("original_variable_name") or name

        if form_name not in G:
            continue

        found = True
        attrs = G.nodes[form_name]

        # Get neighborhood (undirected view — reused for depth>1 BFS)
        undirected = G.to_undirected(as_view=True)
        neighborhood = nx.single_source_shortest_path_length(
            undirected, form_name, cutoff=depth
        )
        neighbor_nodes = set(neighborhood.keys())

        # Collect neighbors grouped by relationship type
        edge_groups = {
            "calculates_from": set(),
            "calculated_by": set(),
            "gated_by": set(),
            "gates": set(),
            "group_gated_by": set(),
            "group_gates": set(),
            "constrained_by": set(),
            "constrains": set(),
            "repeat_sibling": set(),
        }

        def _classify_out(etype, target):
            if etype == "calculates_from":
                edge_groups["calculated_by"].add(target)
            elif etype == "gated_by":
                edge_groups["gates"].add(target)
            elif etype == "group_gated_by":
                edge_groups["group_gates"].add(target)
            elif etype == "constrained_by":
                edge_groups["constrains"].add(target)
            elif etype == "repeat_sibling":
                edge_groups["repeat_sibling"].add(target)

        def _classify_in(etype, target):
            if etype == "calculates_from":
                edge_groups["calculates_from"].add(target)
            elif etype == "gated_by":
                edge_groups["gated_by"].add(target)
            elif etype == "group_gated_by":
                edge_groups["group_gated_by"].add(target)
            elif etype == "constrained_by":
                edge_groups["constrained_by"].add(target)
            elif etype == "repeat_sibling":
                edge_groups["repeat_sibling"].add(target)

        if depth <= 1:
            for _, v, d in G.out_edges(form_name, data=True):
                if v in neighbor_nodes:
                    _classify_out(d.get("type", ""), v)
            for u, _, d in G.in_edges(form_name, data=True):
                if u in neighbor_nodes:
                    _classify_in(d.get("type", ""), u)
        else:
            # Multi-hop: classify each neighbor by the first-hop edge
            first_hop_out = {}
            for _, v, d in G.out_edges(form_name, data=True):
                first_hop_out.setdefault(v, set()).add(d.get("type", ""))
            first_hop_in = {}
            for u, _, d in G.in_edges(form_name, data=True):
                first_hop_in.setdefault(u, set()).add(d.get("type", ""))

            # Single BFS to get all shortest paths at once (reuse undirected view)
            all_paths = nx.single_source_shortest_path(
                undirected, form_name, cutoff=depth
            )
            for node, path in all_paths.items():
                if node == form_name or len(path) < 2:
                    continue
                first_step = path[1]
                for etype in first_hop_out.get(first_step, set()):
                    _classify_out(etype, node)
                for etype in first_hop_in.get(first_step, set()):
                    _classify_in(etype, node)

        # Print output
        print(f"\n[{label}] Variable neighborhood: {form_name} (depth={depth})")
        print(f"  type: {attrs.get('type', '?')}")
        print(f"  group_path: {attrs.get('group_path', '')}")
        print(f"  repeat_depth: {attrs.get('repeat_depth', 0)}")
        rg = attrs.get("repeat_group")
        if rg:
            print(f"  repeat_group: {rg}")
            rg_info = repeat_tree.get(rg)
            if rg_info:
                print(
                    f"  repeat_tree: depth={rg_info['depth']}, "
                    f"count_var={rg_info['count_var']}, "
                    f"count_expr={rg_info.get('count_expr', '?')}, "
                    f"max_iter={rg_info['max_iterations']}, "
                    f"suffix={rg_info['stata_suffix_pattern']}"
                )
                if rg_info.get("parent"):
                    print(f"  repeat_parent: {rg_info['parent']}")
                print(f"  join_key: {rg_info['join_key_note']}")
        sv = attrs.get("stata_vars", [])
        if sv:
            print(f"  stata_vars: {', '.join(sv)}")

        sections = [
            (
                "Calculates from (inputs -- sentinel contamination risk)",
                "calculates_from",
            ),
            (
                "Calculated by (downstream -- changing this changes them)",
                "calculated_by",
            ),
            ("Gated by (missing-by-logic if gate is false)", "gated_by"),
            ("Gates (changing this can make these disappear)", "gates"),
            (
                "Group-gated by (structural gate -- affects whole group)",
                "group_gated_by",
            ),
            ("Group-gates (structural -- these groups depend on this)", "group_gates"),
            ("Constrained by (validation -- defines valid ranges)", "constrained_by"),
            (
                "Constrains (validation -- these depend on valid values here)",
                "constrains",
            ),
            (
                "Repeat siblings (same repeat iteration -- handle together)",
                "repeat_sibling",
            ),
        ]

        for header, key in sections:
            members = edge_groups.get(key, [])
            if not members:
                continue
            print(f"\n  {header}:")
            for m in sorted(members):
                m_attrs = G.nodes.get(m, {})
                m_type = m_attrs.get("type", "?")
                m_depth = m_attrs.get("repeat_depth", 0)
                m_svars = m_attrs.get("stata_vars", [])
                sv_str = f" -> {', '.join(m_svars)}" if m_svars else ""
                depth_str = f" [repeat_depth={m_depth}]" if m_depth > 0 else ""
                print(f"    {m} ({m_type}){depth_str}{sv_str}")

        if all(not edge_groups.get(k) for _, k in sections):
            print("\n  (no relationships found)")

    return found


def repeat_tree(survey_filter: str = None) -> bool:
    """Show the repeat group topology tree from the variable graph."""
    found = False

    for label, files in _filter_surveys(survey_filter).items():
        vpath = files["vardict"]
        if not vpath.exists():
            continue

        graph_path = vpath.with_name(
            vpath.stem.replace("_variable_dictionary", "_variable_graph") + ".json"
        )
        if not graph_path.exists():
            print(f"[{label}] No variable graph found at {graph_path}", file=sys.stderr)
            print(
                f"  Generate it: uv run surveycto-vardict --survey {label}",
                file=sys.stderr,
            )
            continue

        with open(graph_path, encoding="utf-8") as f:
            raw_graph = json.load(f)
        tree = raw_graph.get("repeat_groups", {})

        if not tree:
            print(f"\n[{label}] No repeat groups.")
            found = True
            continue

        found = True
        print(f"\n[{label}] Repeat group topology ({len(tree)} group(s)):")

        for rg_name, info in sorted(tree.items(), key=lambda x: (x[1]["depth"], x[0])):
            indent = "  " * info["depth"]
            print(f"\n{indent}{rg_name}:")
            print(f"{indent}  parent: {info['parent'] or '(root)'}")
            print(f"{indent}  depth: {info['depth']}")
            print(f"{indent}  count_var: {info['count_var']}")
            print(f"{indent}  count_expr: {info.get('count_expr', '?')}")
            print(f"{indent}  max_iterations: {info['max_iterations']}")
            print(f"{indent}  n_variables: {info['n_variables']}")
            if info.get("relevance"):
                print(f"{indent}  relevance: {info['relevance']}")
            print(f"{indent}  stata_suffix: {info['stata_suffix_pattern']}")
            print(f"{indent}  join_key: {info['join_key_note']}")

    return found


def main():
    """Run the search_survey CLI (--var / --search / --choice-list / ...)."""
    if not SURVEY_FILES:
        print(f"WARNING: No survey files found under {DOCS}", file=sys.stderr)
        print(
            "Update DOCS or SURVEY_FILES at the top of search_survey.py.",
            file=sys.stderr,
        )

    parser = argparse.ArgumentParser(description="Survey variable lookup")
    grp = parser.add_mutually_exclusive_group(required=True)
    grp.add_argument(
        "--var", metavar="NAME", help="Look up a Stata variable by exact name"
    )
    grp.add_argument(
        "--choice-list", metavar="LIST", help="List all variables using a choice list"
    )
    grp.add_argument(
        "--search", metavar="TEXT", help="Search question text or variable names"
    )
    grp.add_argument(
        "--gate-chain",
        metavar="NAME",
        help="Show full composed skip logic tree for a variable",
    )
    grp.add_argument(
        "--neighborhood", metavar="NAME", help="Show variable relationship neighborhood"
    )
    grp.add_argument(
        "--repeat-tree", action="store_true", help="Show repeat group topology tree"
    )
    parser.add_argument(
        "--depth",
        metavar="N",
        type=int,
        default=1,
        help="Neighborhood depth for --neighborhood (default: 1)",
    )
    parser.add_argument(
        "--context",
        metavar="N",
        type=int,
        default=0,
        help="Show N adjacent questions on each side + resolve relevance gate (default: 0)",
    )
    parser.add_argument(
        "--survey",
        metavar="KEY",
        default=None,
        help="Filter to surveys whose key contains KEY (e.g. 'endline', 'household', 'baseline')",
    )
    args = parser.parse_args()

    if args.var:
        ok = search_var(args.var, context=args.context, survey_filter=args.survey)
    elif args.choice_list:
        ok = search_choice_list(
            args.choice_list, context=args.context, survey_filter=args.survey
        )
    elif args.gate_chain:
        ok = gate_chain(args.gate_chain, survey_filter=args.survey)
    elif args.neighborhood:
        ok = variable_neighborhood(
            args.neighborhood, depth=args.depth, survey_filter=args.survey
        )
    elif args.repeat_tree:
        ok = repeat_tree(survey_filter=args.survey)
    else:
        ok = search_text(args.search, context=args.context, survey_filter=args.survey)

    if not ok:
        print("No matches found.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
