name: Pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, dev]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Sync (all extras)
        run: uv sync --locked --all-extras
      - uses: pre-commit/action@v3.0.1
